name: 'first-build-action'
description: 'Action to check if this is first run for workflow of a branch.'
author: 'Samhammer AG'
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
    required: true
  branch:
    description: 'Branch for the workflow to look for.'
    required: true
  workflow:
    description: 'Workflow name to look for.'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
