name: test
on:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - id: branch
      run: echo "::set-output name=branch::${GITHUB_REF##*/}" | tr '[:upper:]' '[:lower:]'
    - id: first_run
      uses: SamhammerAG/first-build-action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        workflow: test
        branch: ${{ steps.branch.outputs.branch }}
    - if: steps.first_run.outputs.firstRun == 'true'
      run: echo "Do something on first run"
    - if: steps.first_run.outputs.firstRun == 'false'
      run: echo "Do something on other runs"
